/**
 * ladspa_wrapper.c — LADSPA plugin wrapping enhancer.c float DSP.
 *
 * Coefficients are baked in at build time via eq_coeffs.h (generated by
 * wire.py).  The only runtime parameter is envelope release_secs,
 * exposed as a LADSPA control port (port 4).
 *
 * Build:
 *   make ladspa   (from src/)
 */

#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "enhancer.h"
#include "eq_coeffs.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ── LADSPA types (minimal, self-contained) ─────────────────────────── */

#define LADSPA_PORT_INPUT   0x1
#define LADSPA_PORT_OUTPUT  0x2
#define LADSPA_PORT_AUDIO   0x4
#define LADSPA_PORT_CONTROL 0x8

#define LADSPA_HINT_DEFAULT_MINIMUM 0x4
#define LADSPA_HINT_DEFAULT_MAXIMUM 0x8

typedef float LADSPA_Data;

typedef struct {
    unsigned long UniqueID;
    const char *Label;
    const char *Name;
    const char *Maker;
    const char *Copyright;
    unsigned long PortCount;
    const int *PortDescriptors;
    const char * const *PortNames;
    const void *PortRangeHints;
    void *ImplementationData;
    void *(*instantiate)(const void *Descriptor, unsigned long SampleRate);
    void (*connect_port)(void *Handle, unsigned long Port, LADSPA_Data *DataLocation);
    void (*activate)(void *Handle);
    void (*run)(void *Handle, unsigned long SampleCount);
    void (*run_adding)(void *Handle, unsigned long SampleCount);
    void (*set_run_adding_gain)(void *Handle, LADSPA_Data Gain);
    void (*deactivate)(void *Handle);
    void (*cleanup)(void *Handle);
} LADSPA_Descriptor;

/* ── Plugin instance state ──────────────────────────────────────────── */

typedef struct {
    DspPipe      enh;
    Biquad           *eq_bqs_left;
    Biquad           *eq_bqs_right;
    float             fs;

    /* Connected port buffers */
    LADSPA_Data      *in_left;
    LADSPA_Data      *in_right;
    LADSPA_Data      *out_left;
    LADSPA_Data      *out_right;
    LADSPA_Data      *ctrl_release;
} EqgenInstance;


/* ── Port indices ──────────────────────────────────────────────────── */

enum {
    PORT_IN_L   = 0,
    PORT_IN_R   = 1,
    PORT_OUT_L  = 2,
    PORT_OUT_R  = 3,
    PORT_RELEASE = 4,
    N_PORTS     = 5,
};

#define UNIQUE_ID  0x45475147   /* 'EQGN' */


/* ── instantiate ────────────────────────────────────────────────────── */

static void *eqgen_instantiate(const void *desc, unsigned long fs)
{
    (void)desc;
    EqgenInstance *inst = calloc(1, sizeof(EqgenInstance));
    if (!inst) return NULL;

    int n_bq = EQGEN_N_BIQUADS;
    inst->eq_bqs_left  = calloc((size_t)n_bq, sizeof(Biquad));
    inst->eq_bqs_right = calloc((size_t)n_bq, sizeof(Biquad));
    if ((n_bq > 0) && (!inst->eq_bqs_left || !inst->eq_bqs_right)) {
        free(inst->eq_bqs_left);
        free(inst->eq_bqs_right);
        free(inst);
        return NULL;
    }

    const float *coeffs = eqgen_get_coeffs((int)fs);

    DspPipeCfg cfg;
    dsp_pipe_cfg_init(&cfg,
                         EQGEN_CUTOFF_HZ,
                         EQGEN_H2_AMP,
                         EQGEN_H3_AMP,
                         EQGEN_RELEASE_SECS,
                         (float)fs,
                         EQGEN_PUSH_GAIN,
#ifdef EQGEN_PRE_GAIN
                         EQGEN_PRE_GAIN,
#else
                         1.0f,
#endif
                         EQGEN_N_BIQUADS,
                         coeffs);
    dsp_pipe_init(&inst->enh, &cfg, inst->eq_bqs_left, inst->eq_bqs_right);
    inst->fs = (float)fs;

    return inst;
}


/* ── connect_port ───────────────────────────────────────────────────── */

static void eqgen_connect_port(void *handle, unsigned long port,
                                LADSPA_Data *data)
{
    EqgenInstance *inst = (EqgenInstance *)handle;
    switch (port) {
    case PORT_IN_L:     inst->in_left      = data; break;
    case PORT_IN_R:     inst->in_right     = data; break;
    case PORT_OUT_L:    inst->out_left     = data; break;
    case PORT_OUT_R:    inst->out_right    = data; break;
    case PORT_RELEASE:  inst->ctrl_release = data; break;
    }
}


/* ── activate / deactivate ──────────────────────────────────────────── */

static void eqgen_activate(void *handle)
{
    EqgenInstance *inst = (EqgenInstance *)handle;
    dsp_pipe_reset(&inst->enh);
}

static void eqgen_deactivate(void *handle)
{
    (void)handle;
}


/* ── cleanup ────────────────────────────────────────────────────────── */

static void eqgen_cleanup(void *handle)
{
    EqgenInstance *inst = (EqgenInstance *)handle;
    if (!inst) return;
    free(inst->eq_bqs_left);
    free(inst->eq_bqs_right);
    free(inst);
}


/* ── run ────────────────────────────────────────────────────────────── */

static void eqgen_run(void *handle, unsigned long nframes)
{
    EqgenInstance *inst = (EqgenInstance *)handle;

    /* Check if release control changed → re-init if needed */
    float release = EQGEN_RELEASE_SECS;
    if (inst->ctrl_release && *inst->ctrl_release > 0.001f) {
        release = *inst->ctrl_release;
    }

    static float last_release = EQGEN_RELEASE_SECS;
    static int first_run = 1;
    if (first_run || fabsf(release - last_release) > 0.0001f) {
        first_run = 0;
        last_release = release;
        const float *r_coeffs = eqgen_get_coeffs((int)inst->fs);
        DspPipeCfg cfg;
        dsp_pipe_cfg_init(&cfg,
                             EQGEN_CUTOFF_HZ,
                             EQGEN_H2_AMP,
                             EQGEN_H3_AMP,
                             release,
                             inst->fs,
                             EQGEN_PUSH_GAIN,
#ifdef EQGEN_PRE_GAIN
                             EQGEN_PRE_GAIN,
#else
                             1.0f,
#endif
                             EQGEN_N_BIQUADS,
                             r_coeffs);
        dsp_pipe_init(&inst->enh, &cfg, inst->eq_bqs_left, inst->eq_bqs_right);
    }

    LADSPA_Data *in_l  = inst->in_left;
    LADSPA_Data *in_r  = inst->in_right;
    LADSPA_Data *out_l = inst->out_left;
    LADSPA_Data *out_r = inst->out_right;

    for (unsigned long i = 0; i < nframes; i++) {
        float l = in_l[i];
        float r = in_r[i];

        dsp_pipe_process_stereo(&inst->enh, &l, &r);

        out_l[i] = l;
        out_r[i] = r;
    }
}


/* ── run_adding (unused but must be present) ────────────────────────── */

static void eqgen_run_adding(void *handle, unsigned long nframes)
{
    (void)handle;
    (void)nframes;
}

static void eqgen_set_run_adding_gain(void *handle, LADSPA_Data gain)
{
    (void)handle;
    (void)gain;
}


/* ── Descriptor ─────────────────────────────────────────────────────── */

static const int port_descriptors[N_PORTS] = {
    LADSPA_PORT_INPUT  | LADSPA_PORT_AUDIO,    /* in L  */
    LADSPA_PORT_INPUT  | LADSPA_PORT_AUDIO,    /* in R  */
    LADSPA_PORT_OUTPUT | LADSPA_PORT_AUDIO,    /* out L */
    LADSPA_PORT_OUTPUT | LADSPA_PORT_AUDIO,    /* out R */
    LADSPA_PORT_INPUT  | LADSPA_PORT_CONTROL,  /* release */
};

static const char *port_names[N_PORTS] = {
    "Input L",
    "Input R",
    "Output L",
    "Output R",
    "Release (s)",
};

typedef struct {
    float LowerBound;
    float UpperBound;
    int   HintDescriptor;
    float DefaultLow;
    float DefaultHigh;
} LADSPA_PortRangeHint;

static const LADSPA_PortRangeHint port_hints[N_PORTS] = {
    { 0.0f, 0.0f, 0, 0.0f, 0.0f },
    { 0.0f, 0.0f, 0, 0.0f, 0.0f },
    { 0.0f, 0.0f, 0, 0.0f, 0.0f },
    { 0.0f, 0.0f, 0, 0.0f, 0.0f },
    { 0.01f, 2.0f,
      LADSPA_HINT_DEFAULT_MINIMUM | LADSPA_HINT_DEFAULT_MAXIMUM,
      EQGEN_RELEASE_SECS, EQGEN_RELEASE_SECS },
};

static LADSPA_Descriptor descriptor = {
    .UniqueID          = UNIQUE_ID,
    .Label             = "eqgen",
    .Name              = "EQGen — float EQ + harmonic bass enhancer",
    .Maker             = "eqgen",
    .Copyright         = "None",
    .PortCount         = N_PORTS,
    .PortDescriptors   = port_descriptors,
    .PortNames         = port_names,
    .PortRangeHints    = port_hints,
    .ImplementationData = NULL,
    .instantiate       = eqgen_instantiate,
    .connect_port      = eqgen_connect_port,
    .activate          = eqgen_activate,
    .run               = eqgen_run,
    .run_adding        = eqgen_run_adding,
    .set_run_adding_gain = eqgen_set_run_adding_gain,
    .deactivate        = eqgen_deactivate,
    .cleanup           = eqgen_cleanup,
};


/* ── LADSPA entry point ─────────────────────────────────────────────── */

const LADSPA_Descriptor *ladspa_descriptor(unsigned long index)
{
    return (index == 0) ? &descriptor : NULL;
}
