#!/usr/bin/env python3
"""
Live system-wide EQ via PipeWire null-sink + DSP filter chain.

Usage:
    python -m eqgen.cli.wire setup technics/standing
    python -m eqgen.cli.wire setup -m response.wav -n noise.wav -t target.wav
    python -m eqgen.cli.wire teardown
    python -m eqgen.cli.wire build technics/standing

setup does:
  1. Runs the full EQ pipeline
  2. Fits IIR biquads
  3. Quantizes to Q4.28
  4. Generates src/eq_coeffs.h
  5. Builds enhancer.so + eqgen_ladspa.so + filter
  6. Installs LADSPA plugin to ~/.ladspa/
  7. Creates a null sink + DSP filter chain → wires to hardware output
"""

import argparse
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from eqgen.pipeline import run_pipeline, design_eq, compute_fft_residual, FFT_N
from eqgen.quantize import BiquadQ28, q28_to_float
from eqgen.eq_fit import cascade_response_db, BiquadCoeffs
from eqgen.presets import MAX_IIR_BANDS

MEAS_DIR = ROOT / "measurements"
SRC_DIR = ROOT / "src"
STATE_DIR = Path.home() / ".config" / "eqgen"
STATE_FILE = STATE_DIR / "state.json"


# ── Helpers ───────────────────────────────────────────────────────────

def _run(cmd, **kwargs):
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, **kwargs)


def _pactl(*args):
    return subprocess.run(["pactl"] + list(args), capture_output=True, text=True)


def get_default_sink():
    r = _pactl("get-default-sink")
    return r.stdout.strip() or None


def set_default_sink(name):
    _pactl("set-default-sink", name)


# ── Header generation ─────────────────────────────────────────────────

def generate_eq_header(bq_q28_44, bq_q28_48, bands_44, bands_48, cfg,
                        speaker_name=None, meas_paths=None,
                        bluetooth_id=None, default_volume=32,
                        fft_gains_44=None, fft_gains_48=None):
    """Write src/eq_coeffs.h with baked-in coefficients for both 44.1k and 48k."""
    lines = []
    lines.append("// Auto-generated by eqgen wire — do not edit by hand.")
    lines.append(f"// Source: {' '.join(meas_paths) if meas_paths else 'measurements/' + (speaker_name or 'unknown')}")
    lines.append(f"// Generated: python -m eqgen.cli.wire setup {' '.join(meas_paths) if meas_paths else speaker_name or ''}")
    lines.append(f"// Two coefficient arrays — one per sample rate — because biquad coefficients")
    lines.append(f"// are sample-rate-dependent.  At runtime, eqgen_get_coeffs(rate) selects")
    lines.append(f"// the correct array for 44100 Hz or 48000 Hz.")
    lines.append(f"//")
    lines.append(f"// Biquads: {len(bands_44)} bands (44.1k), {len(bands_48)} bands (48k) — Q4.28 fixed-point")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define EQGEN_CUTOFF_HZ            {cfg['cutoff_hz']:.1f}f")
    lines.append(f"#define EQGEN_H2_AMP               {cfg['h2_amp']:.3f}f")
    lines.append(f"#define EQGEN_H3_AMP               {cfg['h3_amp']:.3f}f")
    lines.append(f"#define EQGEN_RELEASE_SECS         {cfg['release_secs']:.3f}f")
    lines.append(f"#define EQGEN_LIMITER_RELEASE_SECS {cfg['limiter_release_secs']:.3f}f")
    pre_gain = cfg.get('pre_gain', 1.0)
    pre_gain_q16 = int(round(pre_gain * 65536.0))
    lines.append(f"#define EQGEN_PRE_GAIN_Q16          {pre_gain_q16}")
    lines.append(f"#define EQGEN_FS_44100              44100")
    lines.append(f"#define EQGEN_FS_48000              48000")
    lines.append(f"#define EQGEN_N_BIQUADS            {len(bands_44)}")
    bt_name = bluetooth_id if bluetooth_id else "eqgen"
    vol = max(0, min(127, int(default_volume)))
    lines.append(f'#define EQGEN_BT_DEVICE_NAME        "{bt_name}"')
    lines.append(f"#define EQGEN_DEFAULT_VOLUME         {vol}")
    lines.append("")
    # 44100 Hz coefficients
    lines.append(f"static const int32_t eqgen_coeffs_q28_44100[{len(bands_44) * 5}] = {{")
    for i, bq in enumerate(bq_q28_44):
        band = bands_44[i]
        lines.append(
            f"    {bq.b0:>11d}, {bq.b1:>11d}, {bq.b2:>11d}, "
            f"{bq.a1:>11d}, {bq.a2:>11d},"
            f"  // [{i}] f0={band['f0']:6.1f} Hz gain={band['gain_db']:+5.1f} dB"
        )
    lines.append("};")
    lines.append("")
    # 48000 Hz coefficients
    lines.append(f"static const int32_t eqgen_coeffs_q28_48000[{len(bands_48) * 5}] = {{")
    for i, bq in enumerate(bq_q28_48):
        band = bands_48[i]
        lines.append(
            f"    {bq.b0:>11d}, {bq.b1:>11d}, {bq.b2:>11d}, "
            f"{bq.a1:>11d}, {bq.a2:>11d},"
            f"  // [{i}] f0={band['f0']:6.1f} Hz gain={band['gain_db']:+5.1f} dB"
        )
    lines.append("};")
    lines.append("")
    lines.append("#define EQGEN_COEFFS_44100 eqgen_coeffs_q28_44100")
    lines.append("#define EQGEN_COEFFS_48000 eqgen_coeffs_q28_48000")
    lines.append("")
    lines.append("/** Select coefficient array for the given sample rate. */")
    lines.append("static inline const int32_t *eqgen_get_coeffs(int sample_rate) {")
    lines.append("    return (sample_rate == 48000) ? eqgen_coeffs_q28_48000 : eqgen_coeffs_q28_44100;")
    lines.append("}")
    lines.append("")
    lines.append("/** Select nominal Fs for the given sample rate. */")
    lines.append("static inline int eqgen_get_fs(int sample_rate) {")
    lines.append("    return (sample_rate == 48000) ? EQGEN_FS_48000 : EQGEN_FS_44100;")
    lines.append("}")
    lines.append("")

    # ── FFT hybrid EQ gains ───────────────────────────────────────
    if fft_gains_44 is not None and fft_gains_48 is not None:
        n_bins = len(fft_gains_44)
        fft_n = (n_bins - 1) * 2  # bins = N/2 + 1, so N = (bins-1)*2
        lines.append("/* FFT hybrid EQ: per-bin scalar gains for overlap-add treble correction.")
        lines.append(" * EQGEN_FFT_BINS == 0  →  FFT path bypassed at runtime.")
        lines.append(" * EQGEN_FFT_N is the window size (single source of truth for fft_eq.h).")
        lines.append(" */")
        lines.append(f"#define EQGEN_FFT_N    {fft_n}")
        lines.append(f"#define EQGEN_FFT_HOP  {fft_n // 2}    /* N/2 — samples per FFT frame */")
        lines.append(f"#define EQGEN_FFT_BINS {n_bins}    /* N/2 + 1 — gains table entries */")
        lines.append("")

        def _fmt_float(val):
            return f"{val:.8f}f" if abs(val) < 1000 else f"{val:.6e}f"

        lines.append(f"static const float eqgen_fft_gains_44100[{n_bins}] = {{")
        for i in range(0, n_bins, 8):
            chunk = ", ".join(_fmt_float(g) for g in fft_gains_44[i:i+8])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")

        lines.append(f"static const float eqgen_fft_gains_48000[{n_bins}] = {{")
        for i in range(0, n_bins, 8):
            chunk = ", ".join(_fmt_float(g) for g in fft_gains_48[i:i+8])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")

        lines.append("/** Select FFT gains for the given sample rate. */")
        lines.append("static inline const float *eqgen_get_fft_gains(int sample_rate) {")
        lines.append("    return (sample_rate == 48000) ? eqgen_fft_gains_48000 : eqgen_fft_gains_44100;")
        lines.append("}")
    else:
        lines.append("/* FFT hybrid EQ bypassed — no per-bin gains computed. */")
        lines.append("#define EQGEN_FFT_BINS 0")
    lines.append("")

    header_path = SRC_DIR / "eq_coeffs.h"
    header_path.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {header_path}  ({len(bands_44)} bands @ 44.1k, {len(bands_48)} bands @ 48k)")


# ── SFX header generation ────────────────────────────────────────────

SFX_DIR = ROOT / "sfx"
SFX_HEADER = SRC_DIR / "sfx_data.h"


def generate_sfx_header():
    """Convert sfx/*.wav to C arrays in src/sfx_data.h."""
    import struct

    lines = []
    lines.append("// Auto-generated from sfx/*.wav — do not edit by hand.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    for wav_path in sorted(SFX_DIR.glob("*.wav")):
        name = wav_path.stem  # e.g. "connected"
        with open(wav_path, "rb") as f:
            # Parse RIFF WAV header
            riff, size, wave = struct.unpack("<4sI4s", f.read(12))
            if riff != b"RIFF" or wave != b"WAVE":
                print(f"  Skipping {wav_path.name}: not a valid WAV")
                continue

            fmt_tag = channels = sample_rate = bits_per_sample = 0
            data = b""
            while True:
                chunk_id = f.read(4)
                chunk_size = struct.unpack("<I", f.read(4))[0]
                if chunk_id == b"fmt ":
                    fmt = f.read(chunk_size)
                    fmt_tag, channels, sample_rate = struct.unpack_from("<HHI", fmt, 0)
                    if len(fmt) >= 14:
                        bits_per_sample = struct.unpack_from("<H", fmt, 14)[0]
                    else:
                        bits_per_sample = struct.unpack_from("<H", fmt, 12)[0]
                elif chunk_id == b"data":
                    data = f.read(chunk_size)
                    break
                else:
                    f.seek(chunk_size, 1)

            n_samples = len(data) // 2
            lines.append(f"// {name}: {channels}ch, {sample_rate}Hz, {bits_per_sample}-bit, {n_samples} samples")
            lines.append(f"#define SFX_{name.upper()}_SAMPLES {n_samples}")
            lines.append(f"#define SFX_{name.upper()}_RATE    {sample_rate}")
            lines.append(f"static const int16_t sfx_{name}[{n_samples}] = {{")

            # Emit as int16 values, 16 per line
            for i in range(0, len(data), 32):
                chunk = data[i:i+32]
                vals = []
                for j in range(0, len(chunk), 2):
                    if j + 1 < len(chunk):
                        val = struct.unpack_from("<h", chunk, j)[0]
                        vals.append(str(val))
                if vals:
                    lines.append("    " + ", ".join(vals) + ",")

            lines.append("};")
            lines.append("")

    if not lines[3:]:  # no valid WAVs processed
        lines.append("// No SFX WAVs found — all audio callbacks are no-ops.")
        lines.append("#define SFX_DISABLED")
        lines.append("")

    SFX_HEADER.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {SFX_HEADER}")


# ── Pipeline ──────────────────────────────────────────────────────────

def run_full_pipeline(speaker_name=None, meas_paths=None, noise_path=None,
                       target_path=None, fc=60.0, h2=0.5, h3=1.0,
                       max_bands=MAX_IIR_BANDS, smooth_exponent=1.0,
                       target_fs=None, bluetooth_id=None):
    """Run pipeline + IIR fit at both 44100 and 48000, return biquads and config."""
    if speaker_name:
        meas_dir = MEAS_DIR / speaker_name
        if not meas_dir.exists():
            sys.exit(f"ERROR: measurement dir not found: {meas_dir}")
        meas_wavs = sorted(meas_dir.glob("measurement*.wav"))
        if not meas_wavs:
            meas_wavs = sorted(meas_dir.glob("response*.wav"))
        target_wav = meas_dir / "target.wav"
        noise_wav = None
        for nf in ["noise.wav", "noise2.wav", "noise1.wav"]:
            if (meas_dir / nf).exists():
                noise_wav = str(meas_dir / nf)
                break
        if not meas_wavs or not target_wav.exists():
            sys.exit(f"ERROR: need measurement*.wav + target.wav in {meas_dir}")
        meas_paths = [str(p) for p in meas_wavs]
        target_path = str(target_wav)
        noise_path = noise_wav
    else:
        if not meas_paths or not target_path:
            sys.exit("ERROR: need --measurement, --target (or speaker name)")

    print(f"\n── EQ pipeline (Welch + adaptive points + model)...")
    eq_freqs, target_db, fs, max_gain_db = run_pipeline(
        meas_paths, target_path, noise_path,
        bass_enhancer_cutoff=fc, h2=h2, h3=h3,
    )

    print(f"  {len(eq_freqs)} adaptive EQ points, "
          f"{eq_freqs[0]:.0f}–{eq_freqs[-1]:.0f} Hz")
    if max_gain_db > 0:
        print(f"  Max correction gain: {max_gain_db:+.1f} dB")

    # ── FFT + IIR hybrid EQ: FFT handles broad shape, IIR fits narrow residual ─
    rates = [44100.0, 48000.0]
    all_bq_q28 = {}
    all_bands = {}
    all_fft_gains = {}
    all_pre_gains = {}

    for rate in rates:
        # 1. Compute FFT residual (shared helper from pipeline.py)
        _, fft_gains_linear, _, residual_db = compute_fft_residual(
            eq_freqs, target_db, float(rate), FFT_N)

        # 2. Fit IIR biquads to the self-normalizing FFT residual via design_eq()
        print(f"\n── Fitting IIR biquads at {rate:.0f} Hz (max {max_bands} bands) to FFT residual...")
        design_fs = float(rate)
        coeffs, bands, _, fit_target, fitted_db = design_eq(
            eq_freqs, target_db, design_fs,
            max_bands=max_bands, fft_n=FFT_N)

        # 3. Report error
        print(f"  {len(bands)} bands")
        err = fitted_db - fit_target
        for label, lo, hi in [
            ("Bass ≤250Hz", 0, 250), ("Mid 250-2k", 250, 2000),
            ("Treble >2k", 2000, 99999),
        ]:
            m = (eq_freqs >= lo) & (eq_freqs <= hi)
            if m.any():
                print(f"    {label:<16s}  max err = {np.max(np.abs(err[m])):+.1f} dB")

        # 4. Post-hoc pre-gain from the analytical correction curve.
        #    Attenuate before biquads so they never boost past unity.
        #    Close enough to the cascade response — avoids computing it.
        pre_gain = 1.0 / max(1.0, 10.0 ** (max_gain_db / 20.0))

        # 5. Store per-rate results for header generation
        all_bq_q28[rate] = [BiquadQ28(b0=coeffs[i*5], b1=coeffs[i*5+1],
                                      b2=coeffs[i*5+2], a1=coeffs[i*5+3],
                                      a2=coeffs[i*5+4])
                            for i in range(len(bands))]
        all_bands[rate] = bands
        all_fft_gains[rate] = fft_gains_linear.astype(np.float64).tolist()

        all_pre_gains[rate] = pre_gain
        max_residual = np.max(np.abs(residual_db))
        print(f"  FFT EQ: {FFT_N//2 + 1} bins, max residual {max_residual:+.1f} dB")

    bq_q28_44 = all_bq_q28[44100.0]
    bq_q28_48 = all_bq_q28[48000.0]
    bands_44 = all_bands[44100.0]
    bands_48 = all_bands[48000.0]
    fft_gains_44 = all_fft_gains[44100.0]
    fft_gains_48 = all_fft_gains[48000.0]
    # Pre-gain from analytical correction curve peak — attenuates
    # before biquads so cascade never boosts past unity.  Close
    # enough to the actual cascade max.  Volume handled externally.
    pre_gain = all_pre_gains[44100.0]

    cfg = {
        "cutoff_hz": fc, "h2_amp": h2, "h3_amp": h3,
        "release_secs": 0.2, "limiter_release_secs": 0.049,
        "pre_gain": pre_gain,
        "fs": float(fs),
    }

    # Flat coeffs at 44.1k for the streaming filter path (backward compat)
    coeffs_flat = []
    for bq in bq_q28_44:
        coeffs_flat.extend([bq.b0, bq.b1, bq.b2, bq.a1, bq.a2])

    return (eq_freqs, bq_q28_44, bq_q28_48, bands_44, bands_48,
            cfg, coeffs_flat, fft_gains_44, fft_gains_48)


# ── Build & install ───────────────────────────────────────────────────

def build_and_install():
    print(f"\n── Building enhancer.so + filter + ladspa...")
    # Touch filter sources so make rebuilds everything with the freshly-
    # generated eq_coeffs.h (which includes shifted coefficients and
    # EQGEN_PRE_GAIN_Q16).
    for f in ["filter.c", "ladspa/ladspa_wrapper.c"]:
        (SRC_DIR / f).touch()
    r = _run(["make", "-C", str(SRC_DIR), "all"], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
        sys.exit("  ERROR: build failed")

    ladspa_dir = Path.home() / ".ladspa"
    ladspa_dir.mkdir(parents=True, exist_ok=True)
    src = SRC_DIR / "eqgen_ladspa.so"
    dst = ladspa_dir / "eqgen_ladspa.so"
    dst.write_bytes(src.read_bytes())
    print(f"  Installed {dst}")


# ── Wiring ────────────────────────────────────────────────────────────

def _find_hardware_sink():
    """Return the current default if it's hardware, else the best active
    non-eqgen sink (preferring RUNNING > IDLE > SUSPENDED)."""
    default = get_default_sink()
    if default and "eqgen" not in default.lower():
        return default

    r = _pactl("list", "sinks", "short")
    candidates = []
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        name = parts[1]
        if "eqgen" in name.lower():
            continue
        prio = 2  # SUSPENDED or unknown
        if "RUNNING" in line:
            prio = 0
        elif "IDLE" in line:
            prio = 1
        candidates.append((prio, name))

    if candidates:
        candidates.sort()
        return candidates[0][1]
    return None


def _pw_node_serial(node_name):
    """Return object.serial of a PipeWire node by name, or None."""
    r = subprocess.run(
        ["pw-dump"], capture_output=True, text=True, timeout=5)
    if r.returncode != 0:
        return None
    try:
        import json
        data = json.loads(r.stdout)
        for obj in data:
            props = obj.get("info", {}).get("props", {})
            if props.get("node.name") == node_name:
                return props.get("object.serial")
    except (json.JSONDecodeError, KeyError):
        pass
    return None


def setup_wiring(cfg, coeffs_flat):
    """Create a null sink + DSP filter chain, set as default."""

    # Tear down any previous instance first
    if STATE_FILE.exists():
        print(f"\n── Found existing EQGen instance, tearing down...")
        teardown_wiring()
        time.sleep(0.3)

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    state = {**cfg, "coeffs_q28": coeffs_flat,
             "n_biquads": len(coeffs_flat) // 5}

    # Resolve the real hardware output target
    output_sink = _find_hardware_sink()
    if not output_sink:
        sys.exit("ERROR: no hardware sink found")

    state["previous_sink"] = output_sink
    print(f"\n── Hardware output: {output_sink}")

    # 1. Create null sink
    rate = int(cfg["fs"])
    print(f"\n── Creating null sink (eqgen_sink @ {rate} Hz)...")
    r = _pactl("load-module", "module-null-sink",
               "sink_name=eqgen_sink",
               "sink_properties=device.description=EQGen",
               "format=float32le",
               f"rate={rate}",
               "channels=2")
    if r.returncode != 0:
        sys.exit(f"  ERROR: Cannot create null sink: {r.stderr.strip()}")
    null_sink_id = r.stdout.strip()
    state["null_sink_id"] = null_sink_id
    print(f"  Module #{null_sink_id} loaded")

    # 2. Build filter if needed
    filter_bin = SRC_DIR / "eqgen_filter"
    if not filter_bin.exists():
        print(f"\n── Building DSP filter...")
        r = _run(["make", "-C", str(SRC_DIR), "filter"],
                 capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"  ERROR: filter build failed: {r.stderr}")

    # 3. Resolve null sink serial (pw-cat -a needs numeric target)
    null_serial = _pw_node_serial("eqgen_sink")
    if not null_serial:
        sys.exit("ERROR: cannot resolve eqgen_sink serial")

    # 4. Launch filter chain: pw-cat → filter → pw-cat
    # Record: pw-cat -a with numeric serial → captures from eqgen_sink monitor
    # Playback: pw-cat -a --target 0 → creates unlinked ports, we link manually
    print(f"\n── Launching DSP chain (eqgen_sink → filter → {output_sink})...")
    cmd = (
        f"pw-cat -a --record --target {null_serial} "
        f"--format f32 --rate {rate} --channels 2 --latency 20ms - 2>/dev/null | "
        f"{filter_bin} {rate} 2>/tmp/eqgen_filter.log | "
        f"pw-cat -a --playback --target 0 "
        f"--format f32 --rate {rate} --channels 2 --latency 20ms - 2>/dev/null"
    )
    pid_file = STATE_DIR / "filter.pid"
    log_file = STATE_DIR / "filter.log"
    with open(log_file, "w") as lf:
        proc = subprocess.Popen(
            ["bash", "-c", cmd],
            stdout=subprocess.DEVNULL, stderr=lf,
            start_new_session=True,
        )
    pid_file.write_text(str(proc.pid))
    state["filter_pid"] = proc.pid
    time.sleep(0.5)

    # Check it's still alive
    if proc.poll() is not None:
        sys.exit(f"  ERROR: filter chain exited early (see {log_file})")
    print(f"  Filter chain PID {proc.pid} running")

    # 5. Manually link playback pw-cat → hardware output
    print(f"\n── Linking pw-cat → {output_sink}...")
    time.sleep(0.3)
    r = subprocess.run(
        ["pw-link", "pw-cat:output_FL",
         f"{output_sink}:playback_FL"],
        capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"  ERROR: pw-link FL failed: {r.stderr.strip()}")
    r = subprocess.run(
        ["pw-link", "pw-cat:output_FR",
         f"{output_sink}:playback_FR"],
        capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"  ERROR: pw-link FR failed: {r.stderr.strip()}")
    print(f"  Linked pw-cat:output → {output_sink}:playback")

    # 6. Persist state
    with open(str(STATE_FILE), "w") as f:
        json.dump(state, f, indent=2)

    # 5. Set null sink as default
    print(f"\n── Setting eqgen_sink as default...")
    time.sleep(0.3)
    set_default_sink("eqgen_sink")
    time.sleep(0.3)
    new_sink = get_default_sink()
    if new_sink and "eqgen" in new_sink:
        print(f"  Default sink: {new_sink}")
        print(f"\n  ✅ Audio now flows: app → eqgen_sink → filter → {output_sink}")
    else:
        print(f"  Warning: eqgen_sink not set as default (got: {new_sink})")
        teardown_wiring()
        sys.exit(1)

    print(f"  Run 'python -m eqgen.cli.wire teardown' to restore.")


def teardown_wiring():
    """Kill filter chain, unload null sink, restore defaults."""
    state = {}
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE) as f:
                state = json.load(f)
        except (json.JSONDecodeError, OSError):
            print("State file corrupt — cleaning up.")

    # 1. Restore any hardware sink as default (don't trust stale saved state)
    hw_sink = _find_hardware_sink()
    if hw_sink:
        print(f"Restoring default sink: {hw_sink}")
        set_default_sink(hw_sink)
        time.sleep(0.2)

    # 2. Kill filter chain
    filter_pid = state.get("filter_pid")
    if filter_pid:
        try:
            os.kill(int(filter_pid), 0)
            print(f"Stopping filter chain (PID {filter_pid})...")
            os.kill(int(filter_pid), signal.SIGTERM)
            time.sleep(0.3)
            try:
                os.kill(int(filter_pid), signal.SIGKILL)
            except OSError:
                pass
        except OSError:
            pass

    # 3. Unload null sink
    null_sink_id = state.get("null_sink_id")
    if null_sink_id:
        print(f"Unloading null sink #{null_sink_id}...")
        _pactl("unload-module", str(null_sink_id))

    # 4. Fallback: scan for any orphaned eqgen sinks/modules
    r = _pactl("list", "modules", "short")
    for line in r.stdout.splitlines():
        if "eqgen" in line.lower():
            parts = line.split()
            if parts:
                _pactl("unload-module", parts[0])

    # 5. Kill any lingering eqgen_filter processes
    _run(["pkill", "-f", "eqgen_filter"], capture_output=True)

    # 6. Clean up state
    pid_file = STATE_DIR / "filter.pid"
    pid_file.unlink(missing_ok=True)
    STATE_FILE.unlink(missing_ok=True)
    print("  ✅ Teardown complete.")


# ── CLI ───────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="End‑to‑end: measure → build LADSPA plugin → wire to output",
    )
    sub = ap.add_subparsers(dest="command", required=True)

    # setup
    p_setup = sub.add_parser("setup", help="Measure, build, wire")
    p_setup.add_argument("speaker", nargs="?", default=None,
                         help="Speaker name (under measurements/)")
    p_setup.add_argument("-m", "--measurement", nargs="+", default=None,
                         help="Measurement WAV file(s)")
    p_setup.add_argument("-n", "--noise", default=None,
                         help="Noise WAV file")
    p_setup.add_argument("-t", "--target", default=None,
                         help="Target WAV file")
    p_setup.add_argument("--fc", type=float, default=60.0)
    p_setup.add_argument("--h2", type=float, default=0.5)
    p_setup.add_argument("--h3", type=float, default=1.0)
    p_setup.add_argument("--smooth-exponent", type=float, default=1.0)
    p_setup.add_argument("--release", type=float, default=0.2)
    p_setup.add_argument("--limiter-release", type=float, default=0.049)
    p_setup.add_argument("--max-bands", type=int, default=MAX_IIR_BANDS)
    p_setup.add_argument("--bluetooth-id", default=None,
                         help="Bluetooth device name for ESP32 firmware")
    p_setup.add_argument("--preset", default=None,
                         help="Load parameters from a preset JSON (overrides speaker/flags)")
    p_setup.add_argument("--no-wire", action="store_true",
                         help="Build plugin only, don't wire to output")

    # teardown
    sub.add_parser("teardown", help="Remove wiring, restore defaults")

    # build
    p_build = sub.add_parser("build", help="Build firmware from a preset")
    p_build.add_argument("preset", help="Preset name (from presets/ directory)")

    args = ap.parse_args()

    # ── Load preset (build always uses one; setup optionally) ───
    if getattr(args, "preset", None):
        from eqgen.presets import PresetManager
        pm = PresetManager()
        preset = pm.load(args.preset)
        args.speaker = None
        args.measurement = [str(ROOT / p) for p in preset.measurements] if preset.measurements else None
        args.target = str(ROOT / preset.target) if preset.target else None
        args.noise = str(ROOT / preset.noise) if preset.noise else None
        args.fc = preset.fc if preset.fc is not None else args.fc
        args.h2 = preset.h2 if preset.h2 is not None else args.h2
        args.h3 = preset.h3 if preset.h3 is not None else args.h3
        args.max_bands = preset.max_bands if preset.max_bands is not None else args.max_bands
        args.smooth_exponent = preset.smooth_exponent if preset.smooth_exponent is not None else args.smooth_exponent
        args.release = preset.release if preset.release is not None else args.release
        args.limiter_release = preset.limiter_release if preset.limiter_release is not None else args.limiter_release
        args.bluetooth_id = preset.bluetooth_id or args.bluetooth_id
        args.default_volume = preset.default_volume
        print(f"Loaded preset '{args.preset}'")

    if args.command == "teardown":
        teardown_wiring()
        return

    if args.command == "setup":
        if args.speaker and not args.measurement:
            result = run_full_pipeline(
                speaker_name=args.speaker, fc=args.fc, h2=args.h2, h3=args.h3,
                smooth_exponent=args.smooth_exponent,
                max_bands=args.max_bands,
                bluetooth_id=args.bluetooth_id,
            )
        elif args.measurement and args.target:
            result = run_full_pipeline(
                meas_paths=args.measurement, noise_path=args.noise,
                target_path=args.target, fc=args.fc, h2=args.h2, h3=args.h3,
                smooth_exponent=args.smooth_exponent, max_bands=args.max_bands,
                bluetooth_id=args.bluetooth_id,
            )
        else:
            ap.error("Need either speaker name, or -m/-t")

        eq_freqs, bq_q28_44, bq_q28_48, bands_44, bands_48, cfg, coeffs_flat, fft_gains_44, fft_gains_48 = result
        cfg["release_secs"] = args.release
        cfg["limiter_release_secs"] = args.limiter_release

        print(f"\n── Generating headers...")
        generate_eq_header(bq_q28_44, bq_q28_48, bands_44, bands_48, cfg,
                          speaker_name=args.speaker,
                          meas_paths=args.measurement,
                          bluetooth_id=args.bluetooth_id,
                          default_volume=getattr(args, 'default_volume', 32),
                          fft_gains_44=fft_gains_44, fft_gains_48=fft_gains_48)
        generate_sfx_header()

        print(f"\n── Building plugins...")
        build_and_install()

        if not args.no_wire:
            setup_wiring(cfg, coeffs_flat)

    elif args.command == "build":
        result = run_full_pipeline(
            meas_paths=args.measurement, noise_path=args.noise,
            target_path=args.target, fc=args.fc, h2=args.h2, h3=args.h3,
            smooth_exponent=args.smooth_exponent, max_bands=args.max_bands,
            bluetooth_id=args.bluetooth_id,
        )
        eq_freqs, bq_q28_44, bq_q28_48, bands_44, bands_48, cfg, coeffs_flat, fft_gains_44, fft_gains_48 = result
        cfg["release_secs"] = args.release
        cfg["limiter_release_secs"] = args.limiter_release
        generate_eq_header(bq_q28_44, bq_q28_48, bands_44, bands_48, cfg,
                          bluetooth_id=args.bluetooth_id,
                          default_volume=getattr(args, 'default_volume', 32),
                          fft_gains_44=fft_gains_44, fft_gains_48=fft_gains_48)
        generate_sfx_header()
        build_and_install()
        print(f"\n  ✅ Built from preset '{args.preset}'")


if __name__ == "__main__":
    main()
