#!/usr/bin/env python3
"""
Live system-wide EQ via PipeWire null-sink + DSP filter chain.

Usage:
    python -m eqgen.cli.wire setup technics/standing
    python -m eqgen.cli.wire setup -m response.wav -n noise.wav -t target.wav
    python -m eqgen.cli.wire teardown
    python -m eqgen.cli.wire build technics/standing

setup does:
  1. Runs the full EQ pipeline
  2. Fits IIR biquads
  3. Quantizes to Q4.28
  4. Generates src/eq_coeffs.h
  5. Builds enhancer.so + eqgen_ladspa.so + filter
  6. Installs LADSPA plugin to ~/.ladspa/
  7. Creates a null sink + DSP filter chain → wires to hardware output
"""

import argparse
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from eqgen.pipeline import run_pipeline, design_eq
from eqgen.quantize import BiquadQ28, q28_to_float, quantize_biquads_q28
from eqgen.eq_fit import cascade_response_db, BiquadCoeffs, fit_eq_curve

MEAS_DIR = ROOT / "measurements"
SRC_DIR = ROOT / "src"
STATE_DIR = Path.home() / ".config" / "eqgen"
STATE_FILE = STATE_DIR / "state.json"


# ── Helpers ───────────────────────────────────────────────────────────

def _run(cmd, **kwargs):
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, **kwargs)


def _pactl(*args):
    return subprocess.run(["pactl"] + list(args), capture_output=True, text=True)


def get_default_sink():
    r = _pactl("get-default-sink")
    return r.stdout.strip() or None


def set_default_sink(name):
    _pactl("set-default-sink", name)


# ── Header generation ─────────────────────────────────────────────────

def generate_eq_header(bq_q28, bands, cfg):
    """Write src/eq_coeffs.h with baked-in coefficients."""
    lines = []
    lines.append("// Auto-generated by eqgen wire — do not edit by hand.")
    lines.append(f"// {len(bands)} biquads, Q4.28 format")
    lines.append("// Regenerate: python -m eqgen.cli.wire setup ...")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define EQGEN_CUTOFF_HZ            {cfg['cutoff_hz']:.1f}f")
    lines.append(f"#define EQGEN_H2_AMP               {cfg['h2_amp']:.3f}f")
    lines.append(f"#define EQGEN_H3_AMP               {cfg['h3_amp']:.3f}f")
    lines.append(f"#define EQGEN_RELEASE_SECS         {cfg['release_secs']:.3f}f")
    lines.append(f"#define EQGEN_LIMITER_RELEASE_SECS {cfg['limiter_release_secs']:.3f}f")
    lines.append(f"#define EQGEN_FS                   {cfg['fs']:.0f}")
    lines.append(f"#define EQGEN_N_BIQUADS            {len(bands)}")
    lines.append("")
    lines.append(f"static const int32_t eqgen_coeffs_q28[{len(bands) * 5}] = {{")
    for i, bq in enumerate(bq_q28):
        band = bands[i]
        lines.append(
            f"    {bq.b0:>11d}, {bq.b1:>11d}, {bq.b2:>11d}, "
            f"{bq.a1:>11d}, {bq.a2:>11d},"
            f"  // [{i}] f0={band['f0']:6.1f} Hz gain={band['gain_db']:+5.1f} dB"
        )
    lines.append("};")
    lines.append("")

    header_path = SRC_DIR / "eq_coeffs.h"
    header_path.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {header_path}  ({len(bands)} biquads)")


# ── Pipeline ──────────────────────────────────────────────────────────

def run_full_pipeline(speaker_name=None, meas_paths=None, noise_path=None,
                       target_path=None, fc=60.0, h2=0.5, h3=1.0,
                       max_noise=0.65, max_bands=40, target_fs=None):
    """Run pipeline + IIR fit, return biquads and config."""
    if speaker_name:
        meas_dir = MEAS_DIR / speaker_name
        if not meas_dir.exists():
            sys.exit(f"ERROR: measurement dir not found: {meas_dir}")
        meas_wavs = sorted(meas_dir.glob("measurement*.wav"))
        if not meas_wavs:
            meas_wavs = sorted(meas_dir.glob("response*.wav"))
        target_wav = meas_dir / "target.wav"
        noise_wav = None
        for nf in ["noise.wav", "noise2.wav", "noise1.wav"]:
            if (meas_dir / nf).exists():
                noise_wav = str(meas_dir / nf)
                break
        if not meas_wavs or not target_wav.exists():
            sys.exit(f"ERROR: need measurement*.wav + target.wav in {meas_dir}")
        meas_paths = [str(p) for p in meas_wavs]
        target_path = str(target_wav)
        noise_path = noise_wav
    else:
        if not meas_paths or not target_path:
            sys.exit("ERROR: need --measurement, --target (or speaker name)")

    print(f"\n── EQ pipeline (Welch + adaptive points + model)...")
    eq_freqs, target_db, fs = run_pipeline(
        meas_paths, target_path, noise_path,
        bass_enhancer_cutoff=fc, h2=h2, h3=h3, max_noise=max_noise,
    )

    offset_db = float(np.mean(target_db))
    target_db = target_db - offset_db
    print(f"  {len(eq_freqs)} adaptive EQ points, "
          f"{eq_freqs[0]:.0f}–{eq_freqs[-1]:.0f} Hz  "
          f"(offset {offset_db:+.1f} dB)")

    design_fs = float(target_fs) if target_fs else fs
    print(f"\n── Fitting IIR biquads at {design_fs:.0f} Hz (max {max_bands} bands)...")
    fit = fit_eq_curve(eq_freqs, target_db, design_fs, max_bands=max_bands,
                       min_freq=eq_freqs[0], max_freq=eq_freqs[-1],
                       min_peaking_freq=eq_freqs[0])

    bq_q28 = quantize_biquads_q28(fit.biquads)
    print(f"  {len(fit.bands)} bands")

    # Error analysis
    q28_floats = []
    for bq in bq_q28:
        q28_floats.append(BiquadCoeffs(
            b0=q28_to_float(bq.b0), b1=q28_to_float(bq.b1),
            b2=q28_to_float(bq.b2), a1=q28_to_float(bq.a1),
            a2=q28_to_float(bq.a2),
        ))
    fitted_db = cascade_response_db(q28_floats, eq_freqs, design_fs)
    err = fitted_db - target_db
    for label, lo, hi in [
        ("Bass ≤250Hz", 0, 250), ("Mid 250-2k", 250, 2000),
        ("Treble >2k", 2000, 99999),
    ]:
        m = (eq_freqs >= lo) & (eq_freqs <= hi)
        if m.any():
            print(f"    {label:<16s}  max err = {np.max(np.abs(err[m])):+.1f} dB")

    cfg = {
        "cutoff_hz": fc, "h2_amp": h2, "h3_amp": h3,
        "release_secs": 0.2, "limiter_release_secs": 0.049,
        "fs": float(design_fs),
    }

    coeffs_flat = []
    for bq in bq_q28:
        coeffs_flat.extend([bq.b0, bq.b1, bq.b2, bq.a1, bq.a2])

    return eq_freqs, bq_q28, fit.bands, cfg, coeffs_flat


# ── Build & install ───────────────────────────────────────────────────

def build_and_install():
    print(f"\n── Building enhancer.so + eqgen_ladspa.so...")
    r = _run(["make", "-C", str(SRC_DIR), "all"], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
        sys.exit("  ERROR: build failed")

    ladspa_dir = Path.home() / ".ladspa"
    ladspa_dir.mkdir(parents=True, exist_ok=True)
    src = SRC_DIR / "eqgen_ladspa.so"
    dst = ladspa_dir / "eqgen_ladspa.so"
    dst.write_bytes(src.read_bytes())
    print(f"  Installed {dst}")


# ── Wiring ────────────────────────────────────────────────────────────

def setup_wiring(cfg, coeffs_flat):
    """Create a null sink + DSP filter chain, set as default."""

    # Tear down any previous instance first
    if STATE_FILE.exists():
        print(f"\n── Found existing EQGen instance, tearing down...")
        teardown_wiring()
        time.sleep(0.3)

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    state = {**cfg, "coeffs_q28": coeffs_flat,
             "n_biquads": len(coeffs_flat) // 5}

    prev_sink = get_default_sink()
    if not prev_sink:
        sys.exit("ERROR: no default sink found")

    # If we're already the default (e.g. leftover from previous run),
    # find the real hardware sink to use as output target
    if "eqgen" in prev_sink:
        r = _pactl("list", "sinks", "short")
        for line in r.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 2 and "eqgen" not in parts[1].lower():
                prev_sink = parts[1]
                break
        print(f"\n── Current default is eqgen, using hardware sink: {prev_sink}")
    state["previous_sink"] = prev_sink
    print(f"\n── Current default sink: {prev_sink}")

    # 1. Create null sink
    print(f"\n── Creating null sink (eqgen_sink)...")
    r = _pactl("load-module", "module-null-sink",
               "sink_name=eqgen_sink",
               "sink_properties=device.description=EQGen",
               "format=float32le",
               "rate=48000",
               "channels=2")
    if r.returncode != 0:
        sys.exit(f"  ERROR: Cannot create null sink: {r.stderr.strip()}")
    null_sink_id = r.stdout.strip()
    state["null_sink_id"] = null_sink_id
    print(f"  Module #{null_sink_id} loaded")

    # 2. Build filter if needed
    filter_bin = SRC_DIR / "eqgen_filter"
    if not filter_bin.exists():
        print(f"\n── Building DSP filter...")
        r = _run(["make", "-C", str(SRC_DIR), "filter"],
                 capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"  ERROR: filter build failed: {r.stderr}")

    # 3. Launch filter chain: parec → filter → pacat
    print(f"\n── Launching DSP chain (eqgen_sink → filter → {prev_sink})...")
    cmd = (
        f"parec -d eqgen_sink.monitor --format=float32le --rate=48000 "
        f"--latency-msec=20 2>/dev/null | "
        f"{filter_bin} 48000 2>/tmp/eqgen_filter.log | "
        f"pacat -d {prev_sink} --format=float32le --rate=48000 "
        f"--latency-msec=20 2>/dev/null"
    )
    pid_file = STATE_DIR / "filter.pid"
    log_file = STATE_DIR / "filter.log"
    with open(log_file, "w") as lf:
        proc = subprocess.Popen(
            ["bash", "-c", cmd],
            stdout=subprocess.DEVNULL, stderr=lf,
            start_new_session=True,
        )
    pid_file.write_text(str(proc.pid))
    state["filter_pid"] = proc.pid
    time.sleep(0.5)

    # Check it's still alive
    if proc.poll() is not None:
        sys.exit(f"  ERROR: filter chain exited early (see {log_file})")
    print(f"  Filter chain PID {proc.pid} running")

    # 4. Persist state
    with open(str(STATE_FILE), "w") as f:
        json.dump(state, f, indent=2)

    # 5. Set null sink as default
    print(f"\n── Setting eqgen_sink as default...")
    time.sleep(0.3)
    set_default_sink("eqgen_sink")
    time.sleep(0.3)
    new_sink = get_default_sink()
    if new_sink and "eqgen" in new_sink:
        print(f"  Default sink: {new_sink}")
        print(f"\n  ✅ Audio now flows: app → eqgen_sink → filter → {prev_sink}")
    else:
        print(f"  Warning: eqgen_sink not set as default (got: {new_sink})")
        teardown_wiring()
        sys.exit(1)

    print(f"  Run 'python -m eqgen.cli.wire teardown' to restore.")


def teardown_wiring():
    """Kill filter chain, unload null sink, restore defaults."""
    state = {}
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE) as f:
                state = json.load(f)
        except (json.JSONDecodeError, OSError):
            print("State file corrupt — cleaning up.")

    # 1. Restore default sink first
    prev = state.get("previous_sink")
    if prev:
        print(f"Restoring default sink: {prev}")
        set_default_sink(prev)
        time.sleep(0.2)

    # 2. Kill filter chain
    filter_pid = state.get("filter_pid")
    if filter_pid:
        try:
            os.kill(int(filter_pid), 0)
            print(f"Stopping filter chain (PID {filter_pid})...")
            os.kill(int(filter_pid), signal.SIGTERM)
            time.sleep(0.3)
            try:
                os.kill(int(filter_pid), signal.SIGKILL)
            except OSError:
                pass
        except OSError:
            pass

    # 3. Unload null sink
    null_sink_id = state.get("null_sink_id")
    if null_sink_id:
        print(f"Unloading null sink #{null_sink_id}...")
        _pactl("unload-module", str(null_sink_id))

    # 4. Fallback: scan for any orphaned eqgen sinks/modules
    r = _pactl("list", "modules", "short")
    for line in r.stdout.splitlines():
        if "eqgen" in line.lower():
            parts = line.split()
            if parts:
                _pactl("unload-module", parts[0])

    # 5. Kill any lingering eqgen_filter processes
    _run(["pkill", "-f", "eqgen_filter"], capture_output=True)

    # 6. Clean up state
    pid_file = STATE_DIR / "filter.pid"
    pid_file.unlink(missing_ok=True)
    STATE_FILE.unlink(missing_ok=True)
    print("  ✅ Teardown complete.")


# ── CLI ───────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="End‑to‑end: measure → build LADSPA plugin → wire to output",
    )
    sub = ap.add_subparsers(dest="command", required=True)

    # setup
    p_setup = sub.add_parser("setup", help="Measure, build, wire")
    p_setup.add_argument("speaker", nargs="?", default=None,
                         help="Speaker name (under measurements/)")
    p_setup.add_argument("-m", "--measurement", nargs="+", default=None,
                         help="Measurement WAV file(s)")
    p_setup.add_argument("-n", "--noise", default=None,
                         help="Noise WAV file")
    p_setup.add_argument("-t", "--target", default=None,
                         help="Target WAV file")
    p_setup.add_argument("--fc", type=float, default=60.0)
    p_setup.add_argument("--h2", type=float, default=0.5)
    p_setup.add_argument("--h3", type=float, default=1.0)
    p_setup.add_argument("--release", type=float, default=0.2)
    p_setup.add_argument("--max-noise", type=float, default=0.65)
    p_setup.add_argument("--max-bands", type=int, default=40)
    p_setup.add_argument("--no-wire", action="store_true",
                         help="Build plugin only, don't wire to output")

    # teardown
    sub.add_parser("teardown", help="Remove wiring, restore defaults")

    # build
    p_build = sub.add_parser("build", help="Just build the LADSPA plugin")
    p_build.add_argument("speaker", help="Speaker name")
    p_build.add_argument("--fc", type=float, default=60.0)
    p_build.add_argument("--h2", type=float, default=0.5)
    p_build.add_argument("--h3", type=float, default=1.0)
    p_build.add_argument("--max-bands", type=int, default=40)
    p_build.add_argument("--max-noise", type=float, default=0.65)

    args = ap.parse_args()

    if args.command == "teardown":
        teardown_wiring()
        return

    if args.command == "setup":
        if args.speaker and not args.measurement:
            eq_freqs, bq_q28, bands, cfg, coeffs_flat = run_full_pipeline(
                speaker_name=args.speaker, fc=args.fc, h2=args.h2, h3=args.h3,
                max_noise=args.max_noise, max_bands=args.max_bands,
            )
        elif args.measurement and args.target:
            eq_freqs, bq_q28, bands, cfg, coeffs_flat = run_full_pipeline(
                meas_paths=args.measurement, noise_path=args.noise,
                target_path=args.target, fc=args.fc, h2=args.h2, h3=args.h3,
                max_noise=args.max_noise, max_bands=args.max_bands,
            )
        else:
            ap.error("Need either speaker name, or -m/-t")

        cfg["release_secs"] = args.release

        print(f"\n── Generating eq_coeffs.h...")
        generate_eq_header(bq_q28, bands, cfg)

        print(f"\n── Building plugins...")
        build_and_install()

        if not args.no_wire:
            setup_wiring(cfg, coeffs_flat)

    elif args.command == "build":
        eq_freqs, bq_q28, bands, cfg, coeffs_flat = run_full_pipeline(
            speaker_name=args.speaker, fc=args.fc, h2=args.h2, h3=args.h3,
            max_noise=args.max_noise, max_bands=args.max_bands,
        )
        generate_eq_header(bq_q28, bands, cfg)
        build_and_install()
        print(f"\n  ✅ Plugin installed to ~/.ladspa/eqgen_ladspa.so")


if __name__ == "__main__":
    main()
