#!/usr/bin/env python3
"""
Live system-wide EQ via PipeWire null-sink + DSP filter chain.

Usage:
    python -m eqgen.cli.wire setup technics/standing
    python -m eqgen.cli.wire setup -m response.wav -n noise.wav -t target.wav
    python -m eqgen.cli.wire teardown
    python -m eqgen.cli.wire build technics/standing

setup does:
  1. Runs the full EQ pipeline
  2. Fits IIR biquads
  3. Quantizes to Q4.28
  4. Generates src/eq_coeffs.h
  5. Builds enhancer.so + eqgen_ladspa.so + filter
  6. Installs LADSPA plugin to ~/.ladspa/
  7. Creates a null sink + DSP filter chain → wires to hardware output
"""

import argparse
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from eqgen.pipeline import run_pipeline, design_eq
from eqgen.dsp import pre_gain_from_max_gain
from eqgen.eq_fit import cascade_response_db, BiquadCoeffs
from eqgen.presets import MAX_IIR_BANDS, get_house_curve
from eqgen.model import perceptual_weight
from eqgen.smart_volume import SV_LOUDNESS_FC, SV_LOUDNESS_Q, FM_SLOPE
from eqgen.header_gen import generate_c_header

MEAS_DIR = ROOT / "measurements"
SRC_DIR = ROOT / "src"
STATE_DIR = Path.home() / ".config" / "eqgen"
STATE_FILE = STATE_DIR / "state.json"


# ── Helpers ───────────────────────────────────────────────────────────

def _run(cmd, **kwargs):
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, **kwargs)


def _pactl(*args):
    return subprocess.run(["pactl"] + list(args), capture_output=True, text=True)


def get_default_sink():
    r = _pactl("get-default-sink")
    return r.stdout.strip() or None


def set_default_sink(name):
    _pactl("set-default-sink", name)


# ── Header generation ─────────────────────────────────────────────────

def generate_eq_header(biquads_44, biquads_48, bands_44, bands_48, cfg,
                        speaker_name=None, meas_paths=None,
                        bluetooth_id=None, speaker_level=60):
    """Write src/eq_coeffs.h with baked-in float coefficients for both 44.1k and 48k."""
    pre_gain = cfg.get('pre_gain', 1.0)
    bt_name = bluetooth_id if bluetooth_id else "eqgen"

    header_lines = [
        "Auto-generated by eqgen wire — do not edit by hand.",
        f"Source: {' '.join(meas_paths) if meas_paths else 'measurements/' + (speaker_name or 'unknown')}",
        f"Generated: python -m eqgen.cli.wire setup {' '.join(meas_paths) if meas_paths else speaker_name or ''}",
        "Two coefficient arrays — one per sample rate — because biquad coefficients",
        "are sample-rate-dependent.  At runtime, eqgen_get_coeffs(rate) selects",
        "the correct array for 44100 Hz or 48000 Hz.",
        "",
        f"Biquads: {len(bands_44)} bands (44.1k), {len(bands_48)} bands (48k) — float coefficients",
    ]

    define_lines = [
        f"#define EQGEN_CUTOFF_HZ            {cfg['cutoff_hz']:.1f}f",
        f"#define EQGEN_H2_AMP               {cfg['h2_amp']:.4f}f",
        f"#define EQGEN_H3_AMP               {cfg['h3_amp']:.4f}f",
        f"#define EQGEN_PUSH_GAIN            {cfg['push_gain']:.3f}f",
        f"#define EQGEN_OVERBOOST_DB          {cfg.get('overboost_db', 0.0):.2f}f",
        f"#define EQGEN_RELEASE_SECS         {cfg['release_secs']:.3f}f",
        f"#define EQGEN_PRE_GAIN             {pre_gain:.6f}f",
        f"#define EQGEN_FS_44100              44100",
        f"#define EQGEN_FS_48000              48000",
        f"#define EQGEN_N_BIQUADS            {len(bands_44)}",
        f'#define EQGEN_BT_DEVICE_NAME        "{bt_name}"',
        f"#define EQGEN_SPEAKER_LEVEL_DB        {speaker_level}",
        "",
        "/* ── Smart volume (AVRCP-based loudness compensation) ────────────── */",
        "/* 2nd-order low shelf fitted to ISO 226:2023.                         */",
        "/* Shelf boost is linear with dB drop from peak volume.                */",
        f"#define FM_SLOPE                    {FM_SLOPE:.4f}f  /* dB shelf per dB SPL drop */",
        f"#define EQGEN_LOUDNESS_FC_HZ        {SV_LOUDNESS_FC:.1f}f  /* shelf corner freq        */",
        f"#define EQGEN_LOUDNESS_Q            {SV_LOUDNESS_Q:.3f}f  /* shelf Q                  */",
        "",
        "/* Headroom-based enhancer: LP fundamental + harmonics fill available space. */",
        "",
    ]

    content = generate_c_header(
        biquads_44, bands_44,
        biquads_48, bands_48,
        header_lines=header_lines,
        define_lines=define_lines,
    )
    # Append wire-specific footer
    content += "\n/* Biquad-only EQ — no FFT overlap-add. */\n"

    header_path = SRC_DIR / "eq_coeffs.h"
    header_path.write_text(content)
    print(f"  Wrote {header_path}  ({len(bands_44)} bands @ 44.1k, {len(bands_48)} bands @ 48k)")


# ── SFX header generation ────────────────────────────────────────────

SFX_DIR = ROOT / "sfx"
SFX_HEADER = SRC_DIR / "sfx_data.h"


def generate_sfx_header():
    """Convert sfx/*.wav to C arrays in src/sfx_data.h."""
    import struct

    lines = []
    lines.append("// Auto-generated from sfx/*.wav — do not edit by hand.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    for wav_path in sorted(SFX_DIR.glob("*.wav")):
        name = wav_path.stem  # e.g. "connected"
        with open(wav_path, "rb") as f:
            # Parse RIFF WAV header
            riff, size, wave = struct.unpack("<4sI4s", f.read(12))
            if riff != b"RIFF" or wave != b"WAVE":
                print(f"  Skipping {wav_path.name}: not a valid WAV")
                continue

            fmt_tag = channels = sample_rate = bits_per_sample = 0
            data = b""
            while True:
                chunk_id = f.read(4)
                chunk_size = struct.unpack("<I", f.read(4))[0]
                if chunk_id == b"fmt ":
                    fmt = f.read(chunk_size)
                    fmt_tag, channels, sample_rate = struct.unpack_from("<HHI", fmt, 0)
                    if len(fmt) >= 14:
                        bits_per_sample = struct.unpack_from("<H", fmt, 14)[0]
                    else:
                        bits_per_sample = struct.unpack_from("<H", fmt, 12)[0]
                elif chunk_id == b"data":
                    data = f.read(chunk_size)
                    break
                else:
                    f.seek(chunk_size, 1)

            n_samples = len(data) // 2
            lines.append(f"// {name}: {channels}ch, {sample_rate}Hz, {bits_per_sample}-bit, {n_samples} samples")
            lines.append(f"#define SFX_{name.upper()}_SAMPLES {n_samples}")
            lines.append(f"#define SFX_{name.upper()}_RATE    {sample_rate}")
            lines.append(f"static const int16_t sfx_{name}[{n_samples}] = {{")

            # Emit as int16 values, 16 per line
            for i in range(0, len(data), 32):
                chunk = data[i:i+32]
                vals = []
                for j in range(0, len(chunk), 2):
                    if j + 1 < len(chunk):
                        val = struct.unpack_from("<h", chunk, j)[0]
                        vals.append(str(val))
                if vals:
                    lines.append("    " + ", ".join(vals) + ",")

            lines.append("};")
            lines.append("")

    if not lines[3:]:  # no valid WAVs processed
        lines.append("// No SFX WAVs found — all audio callbacks are no-ops.")
        lines.append("#define SFX_DISABLED")
        lines.append("")

    SFX_HEADER.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {SFX_HEADER}")


# ── Pipeline ──────────────────────────────────────────────────────────

def run_full_pipeline(speaker_name=None, meas_paths=None, noise_path=None,
                       target_path=None, fc=60.0,
                       max_bands=MAX_IIR_BANDS, smooth_exponent=1.0,
                       target_fs=None, bluetooth_id=None,
                       house_curve=None, overboost_db=0.0,
                       power_save=0.0):
    """Run pipeline + IIR fit at both 44100 and 48000, return biquads and config."""
    if speaker_name:
        meas_dir = MEAS_DIR / speaker_name
        if not meas_dir.exists():
            sys.exit(f"ERROR: measurement dir not found: {meas_dir}")
        meas_wavs = sorted(meas_dir.glob("measurement*.wav"))
        if not meas_wavs:
            meas_wavs = sorted(meas_dir.glob("response*.wav"))
        target_wav = meas_dir / "target.wav"
        noise_wav = None
        for nf in ["noise.wav", "noise2.wav", "noise1.wav"]:
            if (meas_dir / nf).exists():
                noise_wav = str(meas_dir / nf)
                break
        if not meas_wavs or not target_wav.exists():
            sys.exit(f"ERROR: need measurement*.wav + target.wav in {meas_dir}")
        meas_paths = [str(p) for p in meas_wavs]
        target_path = str(target_wav)
        noise_path = noise_wav
    else:
        if not meas_paths or not target_path:
            sys.exit("ERROR: need --measurement, --target (or speaker name)")

    print(f"\n── EQ pipeline (Welch + adaptive points + model)...")
    eq_freqs, target_db, fs, max_gain_db, efficacy = run_pipeline(
        meas_paths, target_path, noise_path,
        bass_enhancer_cutoff=fc,
        house_curve=house_curve,
    )

    print(f"  {len(eq_freqs)} adaptive EQ points, "
          f"{eq_freqs[0]:.0f}–{eq_freqs[-1]:.0f} Hz")
    if max_gain_db > 0:
        print(f"  Max correction gain: {max_gain_db:+.1f} dB")

    # ── IIR-only EQ ─
    if max_bands > 0:
        rates = [44100.0, 48000.0]
        all_biquads = {}
        all_bands = {}

        for rate in rates:
            print(f"\n── Fitting IIR biquads at {rate:.0f} Hz (max {max_bands} bands)...")
            coeffs, bands, _, fit_target, fitted_db = design_eq(
                eq_freqs, target_db, float(rate),
                max_bands=max_bands,
                min_peaking_freq=fc,
                error_weight=perceptual_weight)

            print(f"  {len(bands)} bands")
            err = fitted_db - fit_target
            for label, lo, hi in [
                ("Bass ≤250Hz", 0, 250), ("Mid 250-2k", 250, 2000),
                ("Treble >2k", 2000, 99999),
            ]:
                m = (eq_freqs >= lo) & (eq_freqs <= hi)
                if m.any():
                    print(f"    {label:<16s}  max err = {np.max(np.abs(err[m])):+.1f} dB")

            all_biquads[rate] = [BiquadCoeffs(b0=coeffs[i*5], b1=coeffs[i*5+1],
                                              b2=coeffs[i*5+2], a1=coeffs[i*5+3],
                                              a2=coeffs[i*5+4])
                                 for i in range(len(bands))]
            all_bands[rate] = bands

        biquads_44 = all_biquads[44100.0]
        biquads_48 = all_biquads[48000.0]
        bands_44 = all_bands[44100.0]
        bands_48 = all_bands[48000.0]
        pre_gain = pre_gain_from_max_gain(max_gain_db)
    else:
        print(f"\n── Skipping IIR fit (max_bands=0)")
        biquads_44 = []
        biquads_48 = []
        bands_44 = []
        bands_48 = []
        pre_gain = 1.0
    # push_gain floor from power_save: 0 → 1.0 (off), 1 → 0.1 (-20dB, max save)
    push_gain_floor = 10.0 ** ((power_save * -20.0) / 20.0)

    cfg = {
        "cutoff_hz": fc,
        "h2_amp": efficacy["h2_amp"],
        "h3_amp": efficacy["h3_amp"],
        "release_secs": 0.2,
        "push_gain": push_gain_floor,
        "overboost_db": overboost_db,
        "pre_gain": pre_gain,
        "fs": float(fs),
    }

    # Flat coeffs at 44.1k for the streaming filter path
    coeffs_flat = []
    for bc in biquads_44:
        coeffs_flat.extend([bc.b0, bc.b1, bc.b2, bc.a1, bc.a2])

    return (eq_freqs, biquads_44, biquads_48, bands_44, bands_48,
            cfg, coeffs_flat)


# ── Build & install ───────────────────────────────────────────────────

def build_and_install():
    print(f"\n── Building enhancer.so + filter + ladspa...")
    # Touch filter sources so make rebuilds everything with the freshly-
    # generated eq_coeffs.h (which includes shifted coefficients and
    # EQGEN_PRE_GAIN).
    for f in ["filter.c", "ladspa/ladspa_wrapper.c"]:
        (SRC_DIR / f).touch()
    r = _run(["make", "-C", str(SRC_DIR), "all"], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
        sys.exit("  ERROR: build failed")

    ladspa_dir = Path.home() / ".ladspa"
    ladspa_dir.mkdir(parents=True, exist_ok=True)
    src = SRC_DIR / "eqgen_ladspa.so"
    dst = ladspa_dir / "eqgen_ladspa.so"
    dst.write_bytes(src.read_bytes())
    print(f"  Installed {dst}")


# ── Wiring ────────────────────────────────────────────────────────────

def _find_hardware_sink():
    """Return the current default if it's hardware, else the best active
    non-eqgen sink (preferring RUNNING > IDLE > SUSPENDED)."""
    default = get_default_sink()
    if default and "eqgen" not in default.lower():
        return default

    r = _pactl("list", "sinks", "short")
    candidates = []
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        name = parts[1]
        if "eqgen" in name.lower():
            continue
        prio = 2  # SUSPENDED or unknown
        if "RUNNING" in line:
            prio = 0
        elif "IDLE" in line:
            prio = 1
        candidates.append((prio, name))

    if candidates:
        candidates.sort()
        return candidates[0][1]
    return None


def _pw_node_serial(node_name):
    """Return object.serial of a PipeWire node by name, or None."""
    r = subprocess.run(
        ["pw-dump"], capture_output=True, text=True, timeout=5)
    if r.returncode != 0:
        return None
    try:
        import json
        data = json.loads(r.stdout)
        for obj in data:
            props = obj.get("info", {}).get("props", {})
            if props.get("node.name") == node_name:
                return props.get("object.serial")
    except (json.JSONDecodeError, KeyError):
        pass
    return None


def setup_wiring(cfg, coeffs_flat, knob_device=None):
    """Create a null sink + DSP filter chain, set as default."""

    # Tear down any previous instance first
    if STATE_FILE.exists():
        print(f"\n── Found existing EQGen instance, tearing down...")
        teardown_wiring()
        time.sleep(0.3)

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    state = {**cfg, "coeffs": coeffs_flat,
             "n_biquads": len(coeffs_flat) // 5}

    # Resolve the real hardware output target
    output_sink = _find_hardware_sink()
    if not output_sink:
        sys.exit("ERROR: no hardware sink found")

    state["previous_sink"] = output_sink
    print(f"\n── Hardware output: {output_sink}")

    # 1. Create null sink
    rate = int(cfg["fs"])
    print(f"\n── Creating null sink (eqgen_sink @ {rate} Hz)...")
    r = _pactl("load-module", "module-null-sink",
               "sink_name=eqgen_sink",
               "sink_properties=device.description=EQGen",
               "format=float32le",
               f"rate={rate}",
               "channels=2")
    if r.returncode != 0:
        sys.exit(f"  ERROR: Cannot create null sink: {r.stderr.strip()}")
    null_sink_id = r.stdout.strip()
    state["null_sink_id"] = null_sink_id
    print(f"  Module #{null_sink_id} loaded")

    # 2. Build filter if needed
    filter_bin = SRC_DIR / "eqgen_filter"
    if not filter_bin.exists():
        print(f"\n── Building DSP filter...")
        r = _run(["make", "-C", str(SRC_DIR), "filter"],
                 capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"  ERROR: filter build failed: {r.stderr}")

    # 3. Resolve null sink serial (pw-cat -a needs numeric target)
    null_serial = _pw_node_serial("eqgen_sink")
    if not null_serial:
        sys.exit("ERROR: cannot resolve eqgen_sink serial")

    # 4. Create control FIFO for live smart-volume adjustments
    ctrl_path = "/tmp/eqgen_sv_fifo"
    if os.path.exists(ctrl_path):
        os.remove(ctrl_path)
    os.mkfifo(ctrl_path)
    print(f"  Created control FIFO: {ctrl_path}")

    # 4b. Launch filter chain: pw-cat → filter → pw-cat
    # Record: pw-cat -a with numeric serial → captures from eqgen_sink monitor
    # Playback: pw-cat -a --target 0 → creates unlinked ports, we link manually
    print(f"\n── Launching DSP chain (eqgen_sink → filter → {output_sink})...")
    cmd = (
        f"pw-cat -a --record --target {null_serial} "
        f"--format f32 --rate {rate} --channels 2 --latency 20ms - 2>/dev/null | "
        f"{filter_bin} {rate} 2>/tmp/eqgen_filter.log | "
        f"pw-cat -a --playback --target 0 "
        f"--format f32 --rate {rate} --channels 2 --latency 20ms - 2>/dev/null"
    )
    pid_file = STATE_DIR / "filter.pid"
    log_file = STATE_DIR / "filter.log"
    with open(log_file, "w") as lf:
        proc = subprocess.Popen(
            ["bash", "-c", cmd],
            stdout=subprocess.DEVNULL, stderr=lf,
            start_new_session=True,
        )
    pid_file.write_text(str(proc.pid))
    state["filter_pid"] = proc.pid
    time.sleep(0.5)

    # Check it's still alive
    if proc.poll() is not None:
        sys.exit(f"  ERROR: filter chain exited early (see {log_file})")
    print(f"  Filter chain PID {proc.pid} running")

    # 5. Manually link playback pw-cat → hardware output
    print(f"\n── Linking pw-cat → {output_sink}...")
    time.sleep(0.3)
    r = subprocess.run(
        ["pw-link", "pw-cat:output_FL",
         f"{output_sink}:playback_FL"],
        capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"  ERROR: pw-link FL failed: {r.stderr.strip()}")
    r = subprocess.run(
        ["pw-link", "pw-cat:output_FR",
         f"{output_sink}:playback_FR"],
        capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"  ERROR: pw-link FR failed: {r.stderr.strip()}")
    print(f"  Linked pw-cat:output → {output_sink}:playback")

    # 6. Persist state
    with open(str(STATE_FILE), "w") as f:
        json.dump(state, f, indent=2)

    # 5. Set null sink as default
    print(f"\n── Setting eqgen_sink as default...")
    time.sleep(0.3)
    set_default_sink("eqgen_sink")
    time.sleep(0.3)
    new_sink = get_default_sink()
    if new_sink and "eqgen" in new_sink:
        print(f"  Default sink: {new_sink}")
        print(f"\n  ✅ Audio now flows: app → eqgen_sink → filter → {output_sink}")
    else:
        print(f"  Warning: eqgen_sink not set as default (got: {new_sink})")
        teardown_wiring()
        sys.exit(1)

    # 6. Launch smart-volume knob bridge
    knob_script = ROOT / "tools" / "sv_knob.py"
    state_file = STATE_DIR / "knob_state.json"
    state_file.parent.mkdir(parents=True, exist_ok=True)
    state_file.write_text('{"vol": 63, "knob_enabled": true}')
    print(f"\n── Launching volume knob bridge...")
    knob_args = [sys.executable, str(knob_script),
                 "--step", "2",
                 "--state-file", str(state_file)]
    knob_proc = subprocess.Popen(
        knob_args,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    state["knob_pid"] = knob_proc.pid
    print(f"  Knob bridge PID {knob_proc.pid}")

    # 7. Persist state
    with open(str(STATE_FILE), "w") as f:
        json.dump(state, f, indent=2)


def teardown_wiring():
    """Kill filter chain, unload null sink, restore defaults."""
    state = {}
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE) as f:
                state = json.load(f)
        except (json.JSONDecodeError, OSError):
            print("State file corrupt — cleaning up.")

    # 1. Restore any hardware sink as default (don't trust stale saved state)
    hw_sink = _find_hardware_sink()
    if hw_sink:
        print(f"Restoring default sink: {hw_sink}")
        set_default_sink(hw_sink)
        time.sleep(0.2)

    # 2. Kill filter chain
    filter_pid = state.get("filter_pid")
    if filter_pid:
        try:
            os.kill(int(filter_pid), 0)
            print(f"Stopping filter chain (PID {filter_pid})...")
            os.kill(int(filter_pid), signal.SIGTERM)
            time.sleep(0.3)
            try:
                os.kill(int(filter_pid), signal.SIGKILL)
            except OSError:
                pass
        except OSError:
            pass
    # 2b. Kill knob bridge
    knob_pid = state.get("knob_pid")
    if knob_pid:
        try:
            os.kill(int(knob_pid), 0)
            print(f"Stopping knob bridge (PID {knob_pid})...")
            os.kill(int(knob_pid), signal.SIGTERM)
            time.sleep(0.2)
            try:
                os.kill(int(knob_pid), signal.SIGKILL)
            except OSError:
                pass
        except OSError:
            pass

    # 3. Unload null sink

    # 4. Fallback: scan for any orphaned eqgen sinks/modules
    r = _pactl("list", "modules", "short")
    for line in r.stdout.splitlines():
        if "eqgen" in line.lower():
            parts = line.split()
            if parts:
                _pactl("unload-module", parts[0])

    # 5. Kill any lingering eqgen_filter processes
    _run(["pkill", "-f", "eqgen_filter"], capture_output=True)

    # 6. Clean up state
    pid_file = STATE_DIR / "filter.pid"
    pid_file.unlink(missing_ok=True)
    STATE_FILE.unlink(missing_ok=True)
    print("  ✅ Teardown complete.")


# ── CLI ───────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="End‑to‑end: measure → build LADSPA plugin → wire to output",
    )
    sub = ap.add_subparsers(dest="command", required=True)

    # setup
    p_setup = sub.add_parser("setup", help="Measure, build, wire")
    p_setup.add_argument("preset", help="Preset name (from presets/ directory)")
    p_setup.add_argument("--knob-device", help="Input device for volume knob (auto-detect if omitted)")
    p_setup.add_argument("--no-wire", action="store_true",
                         help="Build plugin only, don't wire to output")

    # teardown
    sub.add_parser("teardown", help="Remove wiring, restore defaults")

    # build
    p_build = sub.add_parser("build", help="Build firmware from a preset")
    p_build.add_argument("preset", help="Preset name (from presets/ directory)")

    args = ap.parse_args()

    if args.command == "teardown":
        teardown_wiring()
        return

    if args.command == "setup":
        from eqgen.presets import PresetManager
        pm = PresetManager()
        preset = pm.load(args.preset)
        print(f"Loaded preset '{args.preset}'")

        result = run_full_pipeline(
            meas_paths=[str(ROOT / p) for p in preset.measurements],
            noise_path=str(ROOT / preset.noise) if preset.noise else None,
            target_path=str(ROOT / preset.target) if preset.target else None,
            fc=preset.fc,
            smooth_exponent=preset.smooth_exponent,
            max_bands=preset.max_bands,
            bluetooth_id=preset.bluetooth_id or None,
            house_curve=get_house_curve(preset.house_curve) if preset.house_curve else None,
            power_save=preset.power_save)

        eq_freqs, biquads_44, biquads_48, bands_44, bands_48, cfg, coeffs_flat = result
        cfg["release_secs"] = preset.release

        print(f"\n── Generating headers...")
        generate_eq_header(biquads_44, biquads_48, bands_44, bands_48, cfg,
                          meas_paths=[str(ROOT / p) for p in preset.measurements],
                          bluetooth_id=preset.bluetooth_id,
                          speaker_level=preset.speaker_level)
        generate_sfx_header()

        print(f"\n── Building plugins...")
        build_and_install()

        if not args.no_wire:
            setup_wiring(cfg, coeffs_flat, knob_device=getattr(args, 'knob_device', None))

    elif args.command == "build":
        from eqgen.presets import PresetManager
        pm = PresetManager()
        preset = pm.load(args.preset)
        print(f"Loaded preset '{args.preset}'")

        result = run_full_pipeline(
            meas_paths=[str(ROOT / p) for p in preset.measurements],
            noise_path=str(ROOT / preset.noise) if preset.noise else None,
            target_path=str(ROOT / preset.target) if preset.target else None,
            fc=preset.fc,
            smooth_exponent=preset.smooth_exponent,
            max_bands=preset.max_bands,
            bluetooth_id=preset.bluetooth_id or None,
            house_curve=get_house_curve(preset.house_curve) if preset.house_curve else None,
            power_save=preset.power_save)
        eq_freqs, biquads_44, biquads_48, bands_44, bands_48, cfg, coeffs_flat = result
        cfg["release_secs"] = preset.release
        generate_eq_header(biquads_44, biquads_48, bands_44, bands_48, cfg,
                          bluetooth_id=preset.bluetooth_id,
                          speaker_level=preset.speaker_level)
        generate_sfx_header()
        build_and_install()
        print(f"\n  ✅ Built from preset '{args.preset}'")


if __name__ == "__main__":
    main()
